### ISSUE TITLE
resolver support special port

### ISSUE THREAD

**Issue by kvchoi** [kwitsch/docker-DnsCacheRefresh#1]
i have a sub dns server use port 533,  for hotspot domain name cache。can your application to support refresh from it？

**Comment by kwitsch** [comment]
A feature for DCR.RESOLVER to additionally accept server:port
The default DNS port 53 would be used if no port is provided.

👍

**Comment by kwitsch** [comment]
Version 1.1.0 supports *server* or *server:port* in DCR.RESOLVER
